import os
f = open("read.txt", "r")
content = f.read()
print(content)
f.close()
f = open("write.txt", "w")
f.write("This is a new line")
f.close()
f = open("write.txt", "a")
f.write("\nThis is an appended line")
f.close()
f = open("write.txt", "r")
content = f.read()
print(content)
f.close()
os.remove("write.txt")
